### ISSUE TITLE
Incorrect information about VK_KHR_ray_query extension

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [SaschaWillems/vulkan.gpuinfo.org#78]
1. https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_query&platform=all
2. we find that there's support for 1080 / 1080 ti
3. find the exact item https://vulkan.gpuinfo.org/listreports.php?devicename=GeForce+GTX+1080+Ti (driver 460.79.0.0, api 1.2.155)
4. open https://vulkan.gpuinfo.org/displayreport.php?id=10058 and download Full JSON profile
5. where VK_KHR_ray_query?

**Comment by SaschaWillems** [comment]
The JSON must comply with the Vulkan profile that matches the version of the device. That profile version doesn't support the ray query extension so it is not exported.

Please note that the JSON is meant for use with device simulation and as such based (as noted above) on Vulkan profiles. It's not a 1:1 export of the report from the database.

Since the data is available in the report, there's no action for me here.
